### ISSUE TITLE
Parse error: syntax error, unexpected 'https' (T_STRING) in /home7/oxglowne/public_html/oxglowcom/oc-includes/htmlpurifier/HTMLPurifier/Lexer/DOMLex.php on line 237

### ISSUE THREAD

**Issue by kw3ku** [osclass/Osclass#2229] opened 2017-09-24 20:20 UTC
This is making the website unusable..

http://oxglow.com.gh

I NEED HELP

**Comment by garciademarina** [comment] 2018-06-18 15:34
We will need more information about how to reproduce your issue. 

I close this issue because of lack of reproducibility.

**Closed by garciademarina** 2018-06-18 15:34 UTC
