### ISSUE TITLE
ImageResizer.php

### ISSUE THREAD

**Issue by lamas525** [osclass/Osclass#1824] opened 2015-01-31 12:36 UTC
Hi guys, when I post new ad with 8(this error is not only for 8) images (2MB for every image). I will get this error. 

Fatal error: Maximum execution time of 90 seconds exceeded in /data/web/virtuals/90256/virtual/www/oc-includes/osclass/classes/ImageResizer.php on line 114

I know its becouse of php settings. But what if I cant change it ? I need to dont get this error.. Tried many settings . Still same. Someone can help me what to do with imageresizer ?

All you can test here: inzertstar.cz

Thanks guys!

**Comment by dev-101** [comment] 2015-01-31 12:39
Well, you can ask your hosting provider to increase max exec time above 90 seconds, but it probably won't happen due security reasons, it is already raised from above the standard 30 ~ 60 seconds. So, in the end, you need a faster server.

**Comment by lamas525** [comment] 2015-01-31 12:41
I have best hosting what they have. They have only VPS where i can change this options. But Its really expensive. It must be another way here. I wont update osclass automaticaly so I can change this file if it will be needed.. Sorry for my english

**Comment by dev-101** [comment] 2015-01-31 12:44
It's a simple math: if your image is 2 MB in size and you have 8 images, you will need 8x more time to process them all. And this is only for a single user, what will happen if another user simultaneously tries to upload and post item with 8 images? You need to set the limits, since your hosting plan cannot keep up. Or use some restrictions in suggestion I've posted above.

**Comment by lamas525** [comment] 2015-01-31 12:55
Yes i know it. But this is good hosting. SSD disks, lot of RAM and XEON procesors. Server have good performance. There is only problem with this time limit. Maybe I just dont know how it works.. or IDK. But i have WordPress on same hosting.. and i can upload 30 images and someone can upload same files too and its ok.. So ..

**Comment by dev-101** [comment] 2015-01-31 12:58
Wait, you have only 2 items on your site with default 640x480 settings and you already have this issues? Many hosting providers claim lots of things, but do not actually deliver.

PS This is not a bug, this should be in posted in forum; issue will be closed by devs.

**Comment by lamas525** [comment] 2015-01-31 13:02
Ok sorry, yes i have only 2 items now. This is really problem for me. I need to let users upload more then 5 items.. I have default setting for sizes of images.. changes just max. file size to 16MB(my php max is 32 but its really lot) and number of images

**Comment by dev-101** [comment] 2015-01-31 13:03
Enable debug mode and see if anything is slowing down your posting process (some plugin, theme mod issue etc.)

http://doc.osclass.org/Debug_PHP_errors

**Comment by garciademarina** [comment] 2016-11-03 15:08
no issue

**Closed by garciademarina** 2016-11-03 15:08 UTC
