### ISSUE TITLE
3.5.8 issue with languages @ item page

### ISSUE THREAD

**Issue by dev-101** [osclass/Osclass#1951] opened 2015-10-16 10:55 UTC
This is related to new params method (confirmed issue):
http://forums.osclass.org/3-5-x/when-i-want-to-change-the-displaying-language-of-the-item-it-produce-not-found/

**Comment by dev-101** [comment] 2015-10-16 12:18
Hi Conejo,
I have checked on 2 setups 3.5.9 (auto, than manual upgrade just in case), but this does not seem to fix the issue for language switch @ item page. Can you re-check this on your end?

**Comment by conejoninja** [comment] 2015-10-16 13:21
I'm not able to reproduce the issue, both urls in version 257 and 259 are identical in my setup

**Comment by dev-101** [comment] 2015-10-16 13:26
Hi Conejo, I have just returned to 357 and it works fine, will find the problematic file/line in a minute...

**Comment by conejoninja** [comment] 2015-10-16 13:28
Please try this change : https://github.com/osclass/Osclass/commit/c7848d474ebca99c973b0dad44986b0e6b609a97

this should be it, for some reason. I worked on my setup without it

**Comment by dev-101** [comment] 2015-10-16 13:29
(before your change c784..) On my 2nd setup it was half-working half-not, erratic without any rule. But in general, it was not working right.

Will check it now.

**Comment by dev-101** [comment] 2015-10-16 13:33
* seems to be working now *

P.S. there's the HTTP_REFERER  @ hUtils.php `if(filter_var(` line, should it be changed as well?

**Comment by conejoninja** [comment] 2015-10-16 13:35
that should be fixed too : https://github.com/osclass/Osclass/blob/master/oc-includes/osclass/helpers/hUtils.php#L265

**Comment by dev-101** [comment] 2015-10-16 13:36
OK fixed :)

**Closed** 2015-10-16 13:50 UTC
