### ISSUE TITLE
osclass server down; so my site is down?

### ISSUE THREAD

**Issue by ideasharer** [osclass/Osclass#1903] opened 2015-08-10 05:38 UTC
Hello, for some reason osclass.org is down and that effects new installations and/or current installations of osclass that are located on other servers. This is fact, and (very) silly. What possible dependencies are within the installation file(s) or the admin dashboard for such an inconvenience to occur? Open Source; granted. But, I have never experienced such a thing. If its for some sort of push of updates or whatever the case may be this should not effect site owners if osclass servers are down (even for .1 second). Sit owners may log-in but thats about it. Site may be live but is 100% broken if osclass servers are down. Kind of weird that such dependencies exist. I also tried to install a fresh copy of osclass on a different domain and when approaching the second step of the installation the connection times out due to same inconvenience and dependency. I did some googling and noticed posts from 8 months back regarding this same matter and it was taken very lightly. Thats no good! Please fix asap. Thanks.

**Comment by conejoninja** [comment] 2015-08-10 05:58
Which version of Osclass are you using?
Was your public website accessible? Was your admin panel accessible?
Could you share your php configuration?

It's true that we had some problems in previous versions (long time ago), but it was fixed in the following versions (fixed now). Your website is not dependent on osclass.org servers at all, it checks for updated (core, plugins and themes) but it does it in a non-blocking way. Your website should still load fine.

**Closed by conejoninja** 2015-08-10 05:58 UTC

**Comment by ideasharer** [comment] 2015-08-10 06:10
Hi, thanks for the quick reply. When osclass servers are down; site owners website is LIVE but broken due do the checking and/or dependencies linked to osclass.org. Try it yourself. As we speak osclass.org servers are down... try logging-in and registering on any osclass installation on any other server. Anyway, the admin panel works (you are able to log-in) but when you try navigating anywhere for a split second it breaks the connection. Please try it yourself; my concern is very similar to what I ran into which you replied to months back. It wasnt solved. Youll see what I am talking about instantly.

**Comment by ideasharer** [comment] 2015-08-10 06:17
Here's what happens with examples... 

As administrator... 

1) I have osclass installed somewhere other than osclass.org and when I try to log-in to my admin panel I am able to when osclass.org or its affiliated servers are down.

2) I am also able to log-in to my /oc-admin panel when osclass.org or its affiliated servers are down.

3) However, when I click any link within the admin panel; the connection times out and I am no longer able to access my admin panel. Whether its the main page or any of its internal links. This only happens when osclass.org or affiliate servers are down. *Very strange; and not to be rude but I consider this a dependency. 

As site visitor... 

1) I am able to access any website powered by osclass even when osclass.org or its affiliated servers are down. 

2) However, I am unable to register, log-in, comments and or do anything other than view existing listings when osclass.org or its affiliated servers are down. *Very strange; and not to be rude but I consider this a dependency.

**Comment by conejoninja** [comment] 2015-08-10 06:24
Which **version** of Osclass are you using?
Could you share your php configuration?
What do you mean with "broken"?

Calls to osclass.org servers only happnes when checking for updates of core, plugins and themes, when installing new geo data (adding a new country or region) or at the homepage of the admin panel to get the latest news (they are cached).

Checking for updates is non-blocking, but maybe under your configuration it is.

We couldn't reproduce this issue on our servers, so we asked you some questions, please answer them and give as much details as possible.

**Comment by ideasharer** [comment] 2015-08-10 06:27
Sir, now that osclass.org is up and running I am able to access everything on my server / osclass installation perfectly fine. However, for the 4-6 hours osclass.org was up and down I was unable to access everything that was mentioned above. When you're down; we're all down. Not entirely down though. However, the admin panel + 95% of the core features of the script are down (e.g., admin panel, user registration/log-in, commenting, etc.). A great test would be to put your servers down for 5 minutes and play around with an osclass installation on any other server. You'll see what I mean literally instantly. 

osclass version = 3.5.7 (downloaded today; first time osclass user)

**Comment by ideasharer** [comment] 2015-08-10 06:31
I am will capture a video of how its working now that osclass.org (or its affiliated servers) are up and running and I will capture a video of how its not working when your servers are down. 

This happens during installation process + post installation. Once again, you'll be able to see for yourself literally instantly if you purposely put your servers down for a few minutes and try playing around with the admin panel and/or as if you're a user on a osclass installed on any other (actual / hosted / live) server.

**Comment by conejoninja** [comment] 2015-08-10 06:34
Could you please share your server's configuration? php.ini, which modules have you installed?

As I said before, we were not able to reproduce this issue. Our websites were working fine even when osclass.org is down.

I don't doubt you experienced some problems, it happened before, I just want to gather more details so we could reproduce it and fix it.

**Comment by ideasharer** [comment] 2015-08-10 06:36
Glad you mentioned "new geo data" --- perhaps that's the issue because that's what was timing out. However, it seems like that is linked to many things which breaks everything until it is properly loaded. 

As far as server configuration; I can not do that. I've never done that before plus I am not the only user of the server my script is installed on. Simply put; everything is working now that osclass.org is up. But from 4PM to 11:30PM PST there was a lot of downtime on osclass.org and when you're down; we're down. Simple as that.

**Comment by ideasharer** [comment] 2015-08-10 06:39
I wish I could be of more assistance by providing such sensitive info. I would be able to capture a video of what happens when you're down compared to when you're not though. 

Since something similar was brought up in the past; is there any way to disable such update checking and/or pulls? I'd rather update everything manually.

**Comment by dev-101** [comment] 2015-08-10 08:05
Hi Conejo, it seems that gnoe (old user from the forum) also had this issue:
http://forums.osclass.org/general-help/my-osclass-site-osclass-market-forums-down-at-the-same-time/

Unfortunately, I was sleeping during this time and have no knowledge to help...

**Comment by conejoninja** [comment] 2015-08-10 09:03
http://php.net/manual/en/function.stream-set-blocking.php

**Comment by ideasharer** [comment] 2015-08-11 06:32
How do i fix this? It's still happening.

**Comment by conejoninja** [comment] 2015-08-11 06:35
What do you mean it's still happening? osclass websites are not down now.

Unfortunately we're unable to reproduce the issue yet, you could try this fix https://github.com/conejoninja/Osclass/commit/e7b75c7126b222257a9ef96cbdab1aa62ae48c01 but others report it doesn't work.

Could you tell us more about your server configuration (os, php version, web server,...)
